# Endpoint raíz
# Validaciones:
# - Que la API este funcionando en el ambiente esperado
GET http://127.0.0.1:8000/
Accept: application/json

###

# Usuarios

# Registrorse
# Rol requerido: invitado
# Validaciones:
# - Que no exista un usuario ya registrado mediante el DNI o correo eléctronico
# - Que el formato de los campos coincidan con los del dominio
POST http://127.0.0.1:8000/register
Content-Type: application/json

{
  "dniNumber": "43855553",
  "dniType": "CÉDULA CIUDADANÍA",
  "firstName": "Claudia",
  "lastName": "Arelis Ochoa",
  "phoneNumber": "3012558423",
  "emailAddress": "claudia@gmail.com"
}

###

# Crear un usuario completo
# Rol requerido: administrador
# Validaciones:
# - Que el email o el DNI no coincidan con los de otro usuario
# - Que el formato de los campos coincidan con los del dominio
POST http://127.0.0.1:8000/admin/create-user
Content-Type: application/json

{
  "dniNumber": "1036928592",
  "dniType": "CÉDULA CIUDADANÍA",
  "firstName": "Pablo",
  "lastName": "Hernandez",
  "phoneNumber": "3024508215",
  "emailAddress": "pablo@gmail.com",
  "status": "ACTIVO",
  "role": "USUARIO"
}

###

# Modificar información completa de un usuario
# Rol requerido: administrador
# Validaciones:
# - Que el usuario exista
# - Que el email o el DNI no coincidan con los de otro usuario
# - Que el formato de los campos coincidan con los del dominio
PUT http://127.0.0.1:8000/admin/update-user/498466cc-b5c8-4a1e-9820-2bd39ed65429
Content-Type: application/json

{
  "dniNumber": "43855553",
  "dniType": "CÉDULA CIUDADANÍA",
  "firstName": "Claudia",
  "lastName": "Arelis Ochoa",
  "phoneNumber": "3024508215",
  "emailAddress": "claudia@gmail.com",
  "role": "USUARIO",
  "status": "INACTIVO"
}

###

# Modificar información de usuario bàsica
# Rol requerido: usuario
# Validaciones:
# - Que el usuario exista
# - Que el email o el DNI no coincidan con los de otro usuario
# - Que el formato de los campos coincidan con los del dominio
PUT http://127.0.0.1:8000/update-user/9d963fef-0c1f-48b7-99eb-03840a95fe5b
Content-Type: application/json

{
  "dniType": "CÉDULA CIUDADANÍA",
  "firstName": "Santiago",
  "lastName": "Valencia",
  "phoneNumber": "3024508215",
  "emailAddress": "santiagovalenciaochoa2005@gmail.com"
}

###

# Iniciar sesión
# Rol requerido: invitado
# Validaciones:
# - Que DNI y correo electrónico coincidian con los de un usuario registrado
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "dniNumber": "1036928592",
  "emailAddress": "fenixcaps@gmail.com"
}

###

# Celdas

# Crear una nueva celda
# Rol requerido: administrador
# Validaciones:
# - Que no se registre una celda con un número de espacio ya asociado a otra celda
# - Que el formato de los campos coincidan con los del dominio
POST http://127.0.0.1:8000/admin/create-cell
Content-Type: application/json

{
  "spaceNumber": "7",
  "vehicleType": "AUTOMÓVIL",
  "status": "DISPONIBLE"
}

###

# Modificar una celda
# Rol requerido: administrador
# Validaciones:
# - Que exista la celda
# - Que el número de celda no coincida con el de otra celda
# - Que el formato de los campos coincidan con los del dominio

PUT http://127.0.0.1:8000/admin/update-cell/c5f96e48-479b-4d05-8ea1-14a6a7c899bb
Content-Type: application/json

{
  "spaceNumber": "3",
  "vehicleType": "AUTOMÓVIL",
  "status": "MANTENIMIENTO"
}


###

# Vehículos

# Crear un nuevo vehículo
# Rol requerido: usuario
# Validaciones:
# - Que no se registre un vehículo sin un ID de usuario asociado
# - Que no se registre un vehiculo con un número de placa ya asociado a otro vehículo
# - Que el formato de los campos coincidan con los del dominio
POST http://127.0.0.1:8000/create-vehicle
Content-Type: application/json

{
  "userId": "f71516bb-24e7-428e-8df6-716a8c80f307",
  "licensePlate": "XDD123",
  "model": "Lambo 296 GTB",
  "vehicleType": "AUTOMÓVIL"
}

###

# Modificar un vehículo
# Rol requerido: usuario
# Validaciones:
# - Queel vehiculo exista
# - Que no se modifique un vehiculo con un número de placa ya asociado a otro vehículo
# - Que el formato de los campos coincidan con los del dominio
PUT http://127.0.0.1:8000/update-vehicle/4423877f-808f-4dde-b8e4-4c66a7f56338
Content-Type: application/json

{
  "licensePlate": "ABC123",
  "model": "Ferrari 296 GTB",
  "vehicleType": "AUTOMÓVIL"
}

###

# Reservas

# Crear una nueva reserva
# Rol requerido: usuario
# Validaciones:
# - Que no se registre una reserva sin un ID de usuario asociado
# - Que no se registre una reserva si la celda se encuentra en un estado diferente a disponible
# - Que no se registre una reserva si el tipo de vehiculo es incompatible con la celda
POST http://127.0.0.1:8000/create-reservation
Content-Type: application/json

{
  "cellId": "edefeed5-735a-4354-96f3-306155155dcb",
  "userId": "f71516bb-24e7-428e-8df6-716a8c80f307",
  "vehicleId": "8a133a1e-9cc7-408d-998d-b742abd3bb82"
}

###

# Cancelar una reserva
# Rol requerido: usuario
# Validaciones:
# - Que exista la reserva
POST http://127.0.0.1:8000/cancel-reservation
Content-Type: application/json

{
  "reservationId": "21bc1236-a47d-4162-8668-19b41c3565b2"
}

###
# Rechazar una reserva
# Rol requerido: administrador
# Validaciones:
# - Que exista la reserva
POST http://127.0.0.1:8000/admin/reject-reservation
Content-Type: application/json

{
  "reservationId": "21bc1236-a47d-4162-8668-19b41c3565b2"
}

###

# Confirmar una reserva
# Rol requerido: administrador
# Validaciones:
# - Que exista la reserva
POST http://127.0.0.1:8000/admin/confirm-reservation
Content-Type: application/json

{
  "reservationId": "21bc1236-a47d-4162-8668-19b41c3565b2"
}

###

# Completar una reserva
# Rol requerido: administrador
# Validaciones:
# - Que exista la reserva
POST http://127.0.0.1:8000/admin/complete-reservation
Content-Type: application/json

{
  "reservationId": "21bc1236-a47d-4162-8668-19b41c3565b2"
}

###

# Obtener todas las reservas
# Rol requerido: administrador
# Validaciones:
# - Que existan reservas
GET http://127.0.0.1:8000/admin/reservations
Content-Type: application/json

###

# Obtener una reserva por su ID
# Validaciones:
# - Que exista la reserva
GET http://127.0.0.1:8000/reservation/21bc1236-a47d-4162-8668-19b41c3565b2
Content-Type: application/json

###

# Obtener todas las reservas de un usuario
# Validaciones:
# - Que exista la reserva
GET http://127.0.0.1:8000/reservations/f71516bb-24e7-428e-8df6-716a8c80f307
Content-Type: application/json

###


# Empleados

# Crear un nuevo empleado
# Rol requerido: administrador
# Validaciones:
# - Que no se registre un empleado sin un ID de usuario asociado
# - Que no se registre un empleado con un ID de usuario ya asociado a otro empleado
# - Que el formato de los campos coincidan con los del dominio
POST http://127.0.0.1:8000/admin/create-employee
Content-Type: application/json

{
  "userId": "9abb2fdd-7658-4c39-8906-2831f3fe2424",
  "position": "GERENTE",
  "status": "VACACIONES",
  "salary": "1000000"
}

###

# Modificar un empleado
# Rol requerido: administrador
# Validaciones:
# - Que exista el empleado
PUT http://127.0.0.1:8000/admin/update-employee/ad70ad07-5504-4607-a4b3-28ccae08a879
Content-Type: application/json

{
  "position": "GERENTE",
  "status": "ACTIVO",
  "salary": "50"
}

