# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/register
Content-Type: application/json

{
  "dniNumber": "1036928592",
  "dniType": "CÉDULA CIUDADANÍA",
  "firstName": "Santiago",
  "lastName": "Valencia",
  "phoneNumber": "3024508215",
  "emailAddress": "svalnciao@cesde.net"
}

###

POST http://127.0.0.1:8000/login
Content-Type: application/json

{
"dniNumber": "1036928592",
"emailAddress": "svalenciao@cesde.net"
}

###

POST http://127.0.0.1:8000/create-cell
Content-Type: application/json

{
"spaceNumber": "8",
"vehicleType": "MOTOCICLETA",
"status": "DISPONIBLE"
}

###

POST http://127.0.0.1:8000/create-vehicle
Content-Type: application/json

{
  "userId": "6eb5d283-4ad9-4fc3-b7e0-7f4476e1a564",
  "licensePlate": "AAB277",
  "model": "Nisan 2021",
  "vehicleType": "MOTOCICLETA"
}

###

POST http://127.0.0.1:8000/create-reservation
Content-Type: application/json

{
  "userId": "6eb5d283-4ad9-4fc3-b7e0-7f4476e1a564",
  "cellId": "de5775b4-681d-41f3-aa76-2a9398cd744a",
  "vehicleId": "7229d94a-0e67-4eb9-9ee6-a4e61b1c8fd9"
}

###

POST http://127.0.0.1:8000/create-employee
Content-Type: application/json

{
  "userId": "6eb5d283-4ad9-4fc3-b7e0-7f4476e1a564",
  "position": "GERENTE",
  "salary": "1000000"
}
