# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/create-vehicle
Content-Type: application/json

{
  "userId": "c16833d6-0b59-4833-8b21-9e166801ecab",
  "licensePlate": "AAA888",
  "model": "Nisan 2021",
  "vehicleType": "AUTOMÓVIL"
}

